POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token:{{token}}

{

  "name":"jyw",
  "idCard": "23333",
  "type": "1"
}
###

GET http://localhost:8000/member/passenger/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###